version: '3.3'

networks:
  mh_network:
    driver: bridge

services:
  nginx:
    container_name: mhc_nginx
    image: nginx:1.23.1-alpine
    depends_on:
      - nodejs
      - mysql-adminer
      - mongo-express
      - jenkins
    restart: always
    networks:
      - mh_network
    volumes:
      - ./mh-nginx/conf.d/:/etc/nginx/conf.d/
      - ./mh-nginx/ssl/:/etc/nginx/ssl/
      - ./mh-reactjs/build/:/home/mh-reactjs/build/
    ports:
      - "80:80"
      - "443:443"

  nodejs:
    container_name: mhc_nodejs
    image: mhi_nodejs:1.0.0
    restart: always
    depends_on:
      - mongo
      - mysql
    networks:
      - mh_network
    build:
      dockerfile: Dockerfile
      context: "./mh-nodejs"
    volumes:
      - ./mh-nodejs/build:/app/build
      - ./mh-nodejs/logs:/app/logs
    ports:
      - "8000:3000"
    environment:
      - DOCKER_PORT=8000
      - CONTAINER_PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mh_database
      - MYSQL_USER=medihome
      - MYSQL_PASSWORD=mh123456

  mysql:
    container_name: mhc_mysql
    image: mysql:8.0.31
    restart: always
    networks:
      - mh_network
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mh-mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=medihome2022
      - MYSQL_DATABASE=mh_database
      - MYSQL_USER=medihome
      - MYSQL_PASSWORD=mh123456
    ports:
      - "23306:3306"

  mongo:
    image: mongo:6.0.2
    container_name: mhc_mongo
    restart: always
    networks:
      - mh_network
    volumes:
      - ./mh-mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Medihome2022
    ports:
      - 27017:27017

  mysql-adminer:
    image: adminer:4.8.1
    container_name: mhc_mysql_adminer
    restart: always
    depends_on:
      - mysql
    networks:
      - mh_network
    ports:
      - 28082:8080

  mongo-express:
    image: mongo-express:0.54
    container_name: mhc_mongo_express
    restart: always
    depends_on:
      - mongo
    networks:
      - mh_network
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Medihome2022
      ME_CONFIG_MONGODB_URL: mongodb://root:Medihome2022@mongo:27017/

  jenkins:
    image: jenkins/jenkins:2.373-alpine-jdk17
    container_name: mhc_jenkins
    restart: on-failure
    networks:
      - mh_network
    user: root
    volumes:
      - ./mh-jenkins/data:/var/jenkins_home
    ports:
      - 18080:8080
      - 50000:50000

